version: '3'

services: 
  webapp: 
    build: 
      context: .
      dockerfile: ./Dockerfile
      args: 
        APACHE_RUN_USER: $APACHE_RUN_USER
        COMPOSER_CACHE_DIR: $COMPOSER_CACHE_DIR
        MYSQL_HOST: $MYSQL_HOST
        MYSQL_USER: $MYSQL_USER
        MYSQL_PASSWORD: $MYSQL_PASSWORD
        MYSQL_DATABASE: $MYSQL_DATABASE
        PHKONDO_DATA_LANG: $PHKONDO_DATA_LANG
    image: webapp:v1
    ports: 
      - 9000:80 
    volumes: 
      - ./www:/var/www/html:z
      - "./php-custom-settings.ini:/usr/local/etc/php/conf.d/php-custom-settings.ini"
    links: 
      - 'db' 
  db: 
    image: mysql:5.6
    volumes: 
      - ./dbfiles:/var/lib/mysql:z
    env_file: .env